# These are supported funding model platforms

github: [orkestral]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: orkestral
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: orkestral
otechie: orkestral
